name: news_breeze
description: "Leitor de noticias moderno utilizando BLoC e MVVM."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0 

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/